### ISSUE TITLE
Xcode: Getting Failed to initialize LlmInference session -> Failed to map, error: Cannot allocate memory 

### ISSUE THREAD

**Issue by Pratik-7i** [google-ai-edge/mediapipe-samples#393]
Working well in Xcode simulator but getting following error for Device:

`Failed to initialize LlmInference session: ; RET_CHECK failure (external/odml/odml/infra/genai/inference/ml_drift/llm/llm_metal_runner.mm:87) llm_runner->model_->Init(llm_config, num_output_heads, std::move(tensor_loader), create_info, sampler_params, &llm_runner->metal_device_) returned INTERNAL: ; RET_CHECK failure (external/odml/odml/infra/genai/inference/utils/llm_utils/memory_mapped_file_posix.cc:86) (data)!=(((void *)-1))Failed to map, error: Cannot allocate memory `

Device is having sufficient memory and the model size is 1.35 GB.

**Comment by whhone** [comment]
May I know how much RAM your macOS has and what was the model you were trying?

**Comment by schmidt-sebastian** [comment]
Note that you may have to increase the memory footprint the app is allowed to consumer:

Please try these two entitlements:

[com.apple.developer.kernel.extended-virtual-addressing](http://go/appledoc/bundleresources/entitlements/com_apple_developer_kernel_extended-virtual-addressing)
[com.apple.developer.kernel.increased-memory-limit](http://go/appledoc/bundleresources/entitlements/com_apple_developer_kernel_increased-memory-limit)

Closing this as this issue is quite old. Let us know if you still need help.
